
[ { id: 'NumberController()',
	longname: 'NumberController',
	name: 'NumberController',
	kind: 'constructor',
	memberof: 'NumberController',
	params: [ [ Object ], [ Object ], [ Object ], [ Object ], [ Object ], [ Object ] ],
	thisvalue: undefined,
	order: 24 },
{ id: 'GUI()',
	longname: 'GUI',
	name: 'GUI',
	kind: 'constructor',
	memberof: 'GUI',
	params: [ [ Object ], [ Object ], [ Object ], [ Object ], [ Object ] ],
	thisvalue: undefined,
	order: 27 },
{ id: 'GUIItem',
	longname: 'GUIItem',
	name: 'GUIItem',
	kind: 'class',
	scope: 'global',
	thisvalue: undefined,
	typicalname: 'item',
	meta:
     { lineno: 12,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 0 },
{ id: 'Controller',
	longname: 'Controller',
	name: 'Controller',
	kind: 'class',
	scope: 'global',
	augments: [ 'GUIItem' ],
	thisvalue: undefined,
	meta:
     { lineno: 77,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 7 },
{ id: 'ColorController',
	longname: 'ColorController',
	name: 'ColorController',
	kind: 'class',
	scope: 'global',
	augments: [ 'Controller' ],
	thisvalue: undefined,
	typicalname: 'controller',
	meta:
     { lineno: 273,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 20 },
{ id: 'NumberController',
	longname: 'NumberController',
	name: 'NumberController',
	kind: 'class',
	scope: 'global',
	augments: [ 'Controller' ],
	thisvalue: undefined,
	meta:
     { lineno: 357,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 23 },
{ id: 'Header',
	longname: 'Header',
	name: 'Header',
	kind: 'class',
	scope: 'global',
	augments: [ 'GUIItem' ],
	thisvalue: undefined,
	meta:
     { lineno: 748,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 25 },
{ id: 'GUI',
	longname: 'GUI',
	name: 'GUI',
	kind: 'class',
	scope: 'global',
	augments: [ 'GUIItem' ],
	thisvalue: undefined,
	typicalname: 'gui',
	meta:
     { lineno: 797,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 26 },
{ id: 'getColorFormat',
	longname: 'getColorFormat',
	name: 'getColorFormat',
	kind: 'function',
	scope: 'global',
	params: [],
	returns: [ [ Object ] ],
	thisvalue: undefined,
	ignore: true,
	meta:
     { lineno: 263,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 19 },
{ id: 'ColorFormat',
	longname: 'ColorFormat',
	name: 'ColorFormat',
	kind: 'typedef',
	scope: 'global',
	thisvalue: undefined,
	properties: [ [ Object ], [ Object ], [ Object ], [ Object ] ],
	ignore: true,
	meta:
     { lineno: 219,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 18 },
{ id: 'GUIItem#parent',
	longname: 'GUIItem#parent',
	name: 'parent',
	kind: 'member',
	scope: 'instance',
	memberof: 'GUIItem',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 17,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 1 },
{ id: 'GUIItem#domElement',
	longname: 'GUIItem#domElement',
	name: 'domElement',
	kind: 'member',
	scope: 'instance',
	memberof: 'GUIItem',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 23,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 2 },
{ id: 'GUIItem#__disabled',
	longname: 'GUIItem#__disabled',
	name: '__disabled',
	kind: 'member',
	scope: 'instance',
	memberof: 'GUIItem',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 33,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 3 },
{ id: 'Controller#object',
	longname: 'Controller#object',
	name: 'object',
	kind: 'member',
	scope: 'instance',
	memberof: 'Controller',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 84,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 8 },
{ id: 'Controller#property',
	longname: 'Controller#property',
	name: 'property',
	kind: 'member',
	scope: 'instance',
	memberof: 'Controller',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 89,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 9 },
{ id: 'Controller#$name',
	longname: 'Controller#$name',
	name: '$name',
	kind: 'member',
	scope: 'instance',
	memberof: 'Controller',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 94,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 10 },
{ id: 'Controller#$widget',
	longname: 'Controller#$widget',
	name: '$widget',
	kind: 'member',
	scope: 'instance',
	memberof: 'Controller',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 100,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 11 },
{ id: 'Controller#__name',
	longname: 'Controller#__name',
	name: '__name',
	kind: 'member',
	scope: 'instance',
	memberof: 'Controller',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 122,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 13 },
{ id: 'Controller#__onChange',
	longname: 'Controller#__onChange',
	name: '__onChange',
	kind: 'member',
	scope: 'instance',
	memberof: 'Controller',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 141,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 15 },
{ id: 'ColorController#$input',
	longname: 'ColorController#$input',
	name: '$input',
	kind: 'member',
	scope: 'instance',
	memberof: 'ColorController',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 280,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 21 },
{ id: 'ColorController#$display',
	longname: 'ColorController#$display',
	name: '$display',
	kind: 'member',
	scope: 'instance',
	memberof: 'ColorController',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 286,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 22 },
{ id: 'GUI#root',
	longname: 'GUI#root',
	name: 'root',
	kind: 'member',
	scope: 'instance',
	description: 'Reference to the outermost GUI, `this` for the root GUI.',
	memberof: 'GUI',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 810,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 28 },
{ id: 'GUI#children',
	longname: 'GUI#children',
	name: 'children',
	kind: 'member',
	scope: 'instance',
	description: 'List of items in this GUI.',
	memberof: 'GUI',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 816,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 29 },
{ id: 'GUI#$children',
	longname: 'GUI#$children',
	name: '$children',
	kind: 'member',
	scope: 'instance',
	description: 'The `div` that contains child elements.',
	memberof: 'GUI',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 824,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 30 },
{ id: 'GUI#$title',
	longname: 'GUI#$title',
	name: '$title',
	kind: 'member',
	scope: 'instance',
	memberof: 'GUI',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 830,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 31 },
{ id: 'GUI#__name',
	longname: 'GUI#__name',
	name: '__name',
	kind: 'member',
	scope: 'instance',
	memberof: 'GUI',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 951,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 37 },
{ id: 'GUI#__closed',
	longname: 'GUI#__closed',
	name: '__closed',
	kind: 'member',
	scope: 'instance',
	memberof: 'GUI',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 974,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 39 },
{ id: 'Controller#parent',
	longname: 'Controller#parent',
	name: 'parent',
	kind: 'member',
	scope: 'instance',
	inherits: 'GUIItem#parent',
	inherited: true,
	overrides: 'GUIItem#parent',
	memberof: 'Controller',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 17,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 42 },
{ id: 'Controller#domElement',
	longname: 'Controller#domElement',
	name: 'domElement',
	kind: 'member',
	scope: 'instance',
	inherits: 'GUIItem#domElement',
	inherited: true,
	overrides: 'GUIItem#domElement',
	memberof: 'Controller',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 23,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 43 },
{ id: 'Controller#__disabled',
	longname: 'Controller#__disabled',
	name: '__disabled',
	kind: 'member',
	scope: 'instance',
	inherits: 'GUIItem#__disabled',
	inherited: true,
	overrides: 'GUIItem#__disabled',
	memberof: 'Controller',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 33,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 44 },
{ id: 'ColorController#object',
	longname: 'ColorController#object',
	name: 'object',
	kind: 'member',
	scope: 'instance',
	inherits: 'Controller#object',
	inherited: true,
	overrides: 'Controller#object',
	memberof: 'ColorController',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 84,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 48 },
{ id: 'ColorController#property',
	longname: 'ColorController#property',
	name: 'property',
	kind: 'member',
	scope: 'instance',
	inherits: 'Controller#property',
	inherited: true,
	overrides: 'Controller#property',
	memberof: 'ColorController',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 89,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 49 },
{ id: 'ColorController#$name',
	longname: 'ColorController#$name',
	name: '$name',
	kind: 'member',
	scope: 'instance',
	inherits: 'Controller#$name',
	inherited: true,
	overrides: 'Controller#$name',
	memberof: 'ColorController',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 94,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 50 },
{ id: 'ColorController#$widget',
	longname: 'ColorController#$widget',
	name: '$widget',
	kind: 'member',
	scope: 'instance',
	inherits: 'Controller#$widget',
	inherited: true,
	overrides: 'Controller#$widget',
	memberof: 'ColorController',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 100,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 51 },
{ id: 'ColorController#__name',
	longname: 'ColorController#__name',
	name: '__name',
	kind: 'member',
	scope: 'instance',
	inherits: 'Controller#__name',
	inherited: true,
	overrides: 'Controller#__name',
	memberof: 'ColorController',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 122,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 53 },
{ id: 'ColorController#__onChange',
	longname: 'ColorController#__onChange',
	name: '__onChange',
	kind: 'member',
	scope: 'instance',
	inherits: 'Controller#__onChange',
	inherited: true,
	overrides: 'Controller#__onChange',
	memberof: 'ColorController',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 141,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 55 },
{ id: 'ColorController#parent',
	longname: 'ColorController#parent',
	name: 'parent',
	kind: 'member',
	scope: 'instance',
	inherits: 'GUIItem#parent',
	inherited: true,
	overrides: 'Controller#parent',
	memberof: 'ColorController',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 17,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 58 },
{ id: 'ColorController#domElement',
	longname: 'ColorController#domElement',
	name: 'domElement',
	kind: 'member',
	scope: 'instance',
	inherits: 'GUIItem#domElement',
	inherited: true,
	overrides: 'Controller#domElement',
	memberof: 'ColorController',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 23,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 59 },
{ id: 'ColorController#__disabled',
	longname: 'ColorController#__disabled',
	name: '__disabled',
	kind: 'member',
	scope: 'instance',
	inherits: 'GUIItem#__disabled',
	inherited: true,
	overrides: 'Controller#__disabled',
	memberof: 'ColorController',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 33,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 60 },
{ id: 'NumberController#object',
	longname: 'NumberController#object',
	name: 'object',
	kind: 'member',
	scope: 'instance',
	inherits: 'Controller#object',
	inherited: true,
	overrides: 'Controller#object',
	memberof: 'NumberController',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 84,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 64 },
{ id: 'NumberController#property',
	longname: 'NumberController#property',
	name: 'property',
	kind: 'member',
	scope: 'instance',
	inherits: 'Controller#property',
	inherited: true,
	overrides: 'Controller#property',
	memberof: 'NumberController',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 89,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 65 },
{ id: 'NumberController#$name',
	longname: 'NumberController#$name',
	name: '$name',
	kind: 'member',
	scope: 'instance',
	inherits: 'Controller#$name',
	inherited: true,
	overrides: 'Controller#$name',
	memberof: 'NumberController',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 94,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 66 },
{ id: 'NumberController#$widget',
	longname: 'NumberController#$widget',
	name: '$widget',
	kind: 'member',
	scope: 'instance',
	inherits: 'Controller#$widget',
	inherited: true,
	overrides: 'Controller#$widget',
	memberof: 'NumberController',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 100,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 67 },
{ id: 'NumberController#__name',
	longname: 'NumberController#__name',
	name: '__name',
	kind: 'member',
	scope: 'instance',
	inherits: 'Controller#__name',
	inherited: true,
	overrides: 'Controller#__name',
	memberof: 'NumberController',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 122,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 69 },
{ id: 'NumberController#__onChange',
	longname: 'NumberController#__onChange',
	name: '__onChange',
	kind: 'member',
	scope: 'instance',
	inherits: 'Controller#__onChange',
	inherited: true,
	overrides: 'Controller#__onChange',
	memberof: 'NumberController',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 141,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 71 },
{ id: 'NumberController#parent',
	longname: 'NumberController#parent',
	name: 'parent',
	kind: 'member',
	scope: 'instance',
	inherits: 'GUIItem#parent',
	inherited: true,
	overrides: 'Controller#parent',
	memberof: 'NumberController',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 17,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 74 },
{ id: 'NumberController#domElement',
	longname: 'NumberController#domElement',
	name: 'domElement',
	kind: 'member',
	scope: 'instance',
	inherits: 'GUIItem#domElement',
	inherited: true,
	overrides: 'Controller#domElement',
	memberof: 'NumberController',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 23,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 75 },
{ id: 'NumberController#__disabled',
	longname: 'NumberController#__disabled',
	name: '__disabled',
	kind: 'member',
	scope: 'instance',
	inherits: 'GUIItem#__disabled',
	inherited: true,
	overrides: 'Controller#__disabled',
	memberof: 'NumberController',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 33,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 76 },
{ id: 'Header#parent',
	longname: 'Header#parent',
	name: 'parent',
	kind: 'member',
	scope: 'instance',
	inherits: 'GUIItem#parent',
	inherited: true,
	overrides: 'GUIItem#parent',
	memberof: 'Header',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 17,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 80 },
{ id: 'Header#domElement',
	longname: 'Header#domElement',
	name: 'domElement',
	kind: 'member',
	scope: 'instance',
	inherits: 'GUIItem#domElement',
	inherited: true,
	overrides: 'GUIItem#domElement',
	memberof: 'Header',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 23,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 81 },
{ id: 'Header#__disabled',
	longname: 'Header#__disabled',
	name: '__disabled',
	kind: 'member',
	scope: 'instance',
	inherits: 'GUIItem#__disabled',
	inherited: true,
	overrides: 'GUIItem#__disabled',
	memberof: 'Header',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 33,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 82 },
{ id: 'GUI#parent',
	longname: 'GUI#parent',
	name: 'parent',
	kind: 'member',
	scope: 'instance',
	inherits: 'GUIItem#parent',
	inherited: true,
	overrides: 'GUIItem#parent',
	memberof: 'GUI',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 17,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 86 },
{ id: 'GUI#domElement',
	longname: 'GUI#domElement',
	name: 'domElement',
	kind: 'member',
	scope: 'instance',
	inherits: 'GUIItem#domElement',
	inherited: true,
	overrides: 'GUIItem#domElement',
	memberof: 'GUI',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 23,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 87 },
{ id: 'GUI#__disabled',
	longname: 'GUI#__disabled',
	name: '__disabled',
	kind: 'member',
	scope: 'instance',
	inherits: 'GUIItem#__disabled',
	inherited: true,
	overrides: 'GUIItem#__disabled',
	memberof: 'GUI',
	type: { names: [ Array ] },
	thisvalue: undefined,
	meta:
     { lineno: 33,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 88 },
{ id: 'GUIItem#enable',
	longname: 'GUIItem#enable',
	name: 'enable',
	kind: 'function',
	scope: 'instance',
	description: 'Enables or sets the enabled state of this item.',
	memberof: 'GUIItem',
	params: [ [ Object ] ],
	examples:
     [ 'controller.enable();\ncontroller.enable( false ); // disable\ncontroller.enable( controller.__disabled ); // toggle' ],
	thisvalue: undefined,
	chainable: true,
	meta:
     { lineno: 46,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 4 },
{ id: 'GUIItem#disable',
	longname: 'GUIItem#disable',
	name: 'disable',
	kind: 'function',
	scope: 'instance',
	description: 'Disables this item.',
	memberof: 'GUIItem',
	params: [],
	thisvalue: undefined,
	chainable: true,
	meta:
     { lineno: 56,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 5 },
{ id: 'GUIItem#destroy',
	longname: 'GUIItem#destroy',
	name: 'destroy',
	kind: 'function',
	scope: 'instance',
	memberof: 'GUIItem',
	params: [],
	thisvalue: undefined,
	meta:
     { lineno: 65,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 6 },
{ id: 'Controller#name',
	longname: 'Controller#name',
	name: 'name',
	kind: 'function',
	scope: 'instance',
	memberof: 'Controller',
	params: [ [ Object ] ],
	thisvalue: undefined,
	chainable: true,
	meta:
     { lineno: 118,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 12 },
{ id: 'Controller#onChange',
	longname: 'Controller#onChange',
	name: 'onChange',
	kind: 'function',
	scope: 'instance',
	memberof: 'Controller',
	params: [ [ Object ] ],
	examples:
     [ 'gui.add( object, \'property\' ).onChange( v => {\n\tconsole.log( \'The value is now \' + v );\n} );' ],
	thisvalue: undefined,
	chainable: true,
	meta:
     { lineno: 137,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 14 },
{ id: 'Controller#getValue',
	longname: 'Controller#getValue',
	name: 'getValue',
	kind: 'function',
	scope: 'instance',
	memberof: 'Controller',
	params: [],
	returns: [ [ Object ] ],
	thisvalue: undefined,
	meta:
     { lineno: 183,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 16 },
{ id: 'Controller#updateDisplay',
	longname: 'Controller#updateDisplay',
	name: 'updateDisplay',
	kind: 'function',
	scope: 'instance',
	memberof: 'Controller',
	params: [],
	thisvalue: undefined,
	meta:
     { lineno: 190,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 17 },
{ id: 'GUI#add',
	longname: 'GUI#add',
	name: 'add',
	kind: 'function',
	scope: 'instance',
	memberof: 'GUI',
	params: [ [ Object ], [ Object ], [ Object ], [ Object ], [ Object ] ],
	returns: [ [ Object ] ],
	thisvalue: undefined,
	meta:
     { lineno: 874,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 32 },
{ id: 'GUI#addColor',
	longname: 'GUI#addColor',
	name: 'addColor',
	kind: 'function',
	scope: 'instance',
	memberof: 'GUI',
	params: [ [ Object ], [ Object ] ],
	returns: [ [ Object ] ],
	thisvalue: undefined,
	meta:
     { lineno: 920,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 33 },
{ id: 'GUI#addHeader',
	longname: 'GUI#addHeader',
	name: 'addHeader',
	kind: 'function',
	scope: 'instance',
	memberof: 'GUI',
	params: [ [ Object ] ],
	returns: [ [ Object ] ],
	thisvalue: undefined,
	meta:
     { lineno: 929,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 34 },
{ id: 'GUI#addFolder',
	longname: 'GUI#addFolder',
	name: 'addFolder',
	kind: 'function',
	scope: 'instance',
	memberof: 'GUI',
	params: [ [ Object ] ],
	returns: [ [ Object ] ],
	thisvalue: undefined,
	meta:
     { lineno: 938,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 35 },
{ id: 'GUI#name',
	longname: 'GUI#name',
	name: 'name',
	kind: 'function',
	scope: 'instance',
	memberof: 'GUI',
	params: [ [ Object ] ],
	thisvalue: undefined,
	chainable: true,
	meta:
     { lineno: 947,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 36 },
{ id: 'GUI#open',
	longname: 'GUI#open',
	name: 'open',
	kind: 'function',
	scope: 'instance',
	memberof: 'GUI',
	params: [ [ Object ] ],
	thisvalue: undefined,
	chainable: true,
	meta:
     { lineno: 970,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 38 },
{ id: 'GUI#close',
	longname: 'GUI#close',
	name: 'close',
	kind: 'function',
	scope: 'instance',
	memberof: 'GUI',
	params: [],
	thisvalue: undefined,
	chainable: true,
	meta:
     { lineno: 982,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 40 },
{ id: 'GUI#destroy',
	longname: 'GUI#destroy',
	name: 'destroy',
	kind: 'function',
	scope: 'instance',
	overrides: 'GUIItem#destroy',
	memberof: 'GUI',
	params: [],
	thisvalue: undefined,
	meta:
     { lineno: 991,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 41 },
{ id: 'Controller#enable',
	longname: 'Controller#enable',
	name: 'enable',
	kind: 'function',
	scope: 'instance',
	inherits: 'GUIItem#enable',
	inherited: true,
	overrides: 'GUIItem#enable',
	description: 'Enables or sets the enabled state of this item.',
	memberof: 'Controller',
	params: [ [ Object ] ],
	examples:
     [ 'controller.enable();\ncontroller.enable( false ); // disable\ncontroller.enable( controller.__disabled ); // toggle' ],
	thisvalue: undefined,
	chainable: true,
	meta:
     { lineno: 46,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 45 },
{ id: 'Controller#disable',
	longname: 'Controller#disable',
	name: 'disable',
	kind: 'function',
	scope: 'instance',
	inherits: 'GUIItem#disable',
	inherited: true,
	overrides: 'GUIItem#disable',
	description: 'Disables this item.',
	memberof: 'Controller',
	thisvalue: undefined,
	chainable: true,
	meta:
     { lineno: 56,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 46 },
{ id: 'Controller#destroy',
	longname: 'Controller#destroy',
	name: 'destroy',
	kind: 'function',
	scope: 'instance',
	inherits: 'GUIItem#destroy',
	inherited: true,
	overrides: 'GUIItem#destroy',
	memberof: 'Controller',
	thisvalue: undefined,
	meta:
     { lineno: 65,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 47 },
{ id: 'ColorController#name',
	longname: 'ColorController#name',
	name: 'name',
	kind: 'function',
	scope: 'instance',
	inherits: 'Controller#name',
	inherited: true,
	overrides: 'Controller#name',
	memberof: 'ColorController',
	params: [ [ Object ] ],
	thisvalue: undefined,
	chainable: true,
	meta:
     { lineno: 118,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 52 },
{ id: 'ColorController#onChange',
	longname: 'ColorController#onChange',
	name: 'onChange',
	kind: 'function',
	scope: 'instance',
	inherits: 'Controller#onChange',
	inherited: true,
	overrides: 'Controller#onChange',
	memberof: 'ColorController',
	params: [ [ Object ] ],
	examples:
     [ 'gui.add( object, \'property\' ).onChange( v => {\n\tconsole.log( \'The value is now \' + v );\n} );' ],
	thisvalue: undefined,
	chainable: true,
	meta:
     { lineno: 137,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 54 },
{ id: 'ColorController#getValue',
	longname: 'ColorController#getValue',
	name: 'getValue',
	kind: 'function',
	scope: 'instance',
	inherits: 'Controller#getValue',
	inherited: true,
	overrides: 'Controller#getValue',
	memberof: 'ColorController',
	returns: [ [ Object ] ],
	thisvalue: undefined,
	meta:
     { lineno: 183,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 56 },
{ id: 'ColorController#updateDisplay',
	longname: 'ColorController#updateDisplay',
	name: 'updateDisplay',
	kind: 'function',
	scope: 'instance',
	inherits: 'Controller#updateDisplay',
	inherited: true,
	overrides: 'Controller#updateDisplay',
	memberof: 'ColorController',
	thisvalue: undefined,
	meta:
     { lineno: 190,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 57 },
{ id: 'ColorController#enable',
	longname: 'ColorController#enable',
	name: 'enable',
	kind: 'function',
	scope: 'instance',
	inherits: 'GUIItem#enable',
	inherited: true,
	overrides: 'Controller#enable',
	description: 'Enables or sets the enabled state of this item.',
	memberof: 'ColorController',
	params: [ [ Object ] ],
	examples:
     [ 'controller.enable();\ncontroller.enable( false ); // disable\ncontroller.enable( controller.__disabled ); // toggle' ],
	thisvalue: undefined,
	chainable: true,
	meta:
     { lineno: 46,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 61 },
{ id: 'ColorController#disable',
	longname: 'ColorController#disable',
	name: 'disable',
	kind: 'function',
	scope: 'instance',
	inherits: 'GUIItem#disable',
	inherited: true,
	overrides: 'Controller#disable',
	description: 'Disables this item.',
	memberof: 'ColorController',
	thisvalue: undefined,
	chainable: true,
	meta:
     { lineno: 56,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 62 },
{ id: 'ColorController#destroy',
	longname: 'ColorController#destroy',
	name: 'destroy',
	kind: 'function',
	scope: 'instance',
	inherits: 'GUIItem#destroy',
	inherited: true,
	overrides: 'Controller#destroy',
	memberof: 'ColorController',
	thisvalue: undefined,
	meta:
     { lineno: 65,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 63 },
{ id: 'NumberController#name',
	longname: 'NumberController#name',
	name: 'name',
	kind: 'function',
	scope: 'instance',
	inherits: 'Controller#name',
	inherited: true,
	overrides: 'Controller#name',
	memberof: 'NumberController',
	params: [ [ Object ] ],
	thisvalue: undefined,
	chainable: true,
	meta:
     { lineno: 118,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 68 },
{ id: 'NumberController#onChange',
	longname: 'NumberController#onChange',
	name: 'onChange',
	kind: 'function',
	scope: 'instance',
	inherits: 'Controller#onChange',
	inherited: true,
	overrides: 'Controller#onChange',
	memberof: 'NumberController',
	params: [ [ Object ] ],
	examples:
     [ 'gui.add( object, \'property\' ).onChange( v => {\n\tconsole.log( \'The value is now \' + v );\n} );' ],
	thisvalue: undefined,
	chainable: true,
	meta:
     { lineno: 137,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 70 },
{ id: 'NumberController#getValue',
	longname: 'NumberController#getValue',
	name: 'getValue',
	kind: 'function',
	scope: 'instance',
	inherits: 'Controller#getValue',
	inherited: true,
	overrides: 'Controller#getValue',
	memberof: 'NumberController',
	returns: [ [ Object ] ],
	thisvalue: undefined,
	meta:
     { lineno: 183,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 72 },
{ id: 'NumberController#updateDisplay',
	longname: 'NumberController#updateDisplay',
	name: 'updateDisplay',
	kind: 'function',
	scope: 'instance',
	inherits: 'Controller#updateDisplay',
	inherited: true,
	overrides: 'Controller#updateDisplay',
	memberof: 'NumberController',
	thisvalue: undefined,
	meta:
     { lineno: 190,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 73 },
{ id: 'NumberController#enable',
	longname: 'NumberController#enable',
	name: 'enable',
	kind: 'function',
	scope: 'instance',
	inherits: 'GUIItem#enable',
	inherited: true,
	overrides: 'Controller#enable',
	description: 'Enables or sets the enabled state of this item.',
	memberof: 'NumberController',
	params: [ [ Object ] ],
	examples:
     [ 'controller.enable();\ncontroller.enable( false ); // disable\ncontroller.enable( controller.__disabled ); // toggle' ],
	thisvalue: undefined,
	chainable: true,
	meta:
     { lineno: 46,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 77 },
{ id: 'NumberController#disable',
	longname: 'NumberController#disable',
	name: 'disable',
	kind: 'function',
	scope: 'instance',
	inherits: 'GUIItem#disable',
	inherited: true,
	overrides: 'Controller#disable',
	description: 'Disables this item.',
	memberof: 'NumberController',
	thisvalue: undefined,
	chainable: true,
	meta:
     { lineno: 56,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 78 },
{ id: 'NumberController#destroy',
	longname: 'NumberController#destroy',
	name: 'destroy',
	kind: 'function',
	scope: 'instance',
	inherits: 'GUIItem#destroy',
	inherited: true,
	overrides: 'Controller#destroy',
	memberof: 'NumberController',
	thisvalue: undefined,
	meta:
     { lineno: 65,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 79 },
{ id: 'Header#enable',
	longname: 'Header#enable',
	name: 'enable',
	kind: 'function',
	scope: 'instance',
	inherits: 'GUIItem#enable',
	inherited: true,
	overrides: 'GUIItem#enable',
	description: 'Enables or sets the enabled state of this item.',
	memberof: 'Header',
	params: [ [ Object ] ],
	examples:
     [ 'controller.enable();\ncontroller.enable( false ); // disable\ncontroller.enable( controller.__disabled ); // toggle' ],
	thisvalue: undefined,
	chainable: true,
	meta:
     { lineno: 46,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 83 },
{ id: 'Header#disable',
	longname: 'Header#disable',
	name: 'disable',
	kind: 'function',
	scope: 'instance',
	inherits: 'GUIItem#disable',
	inherited: true,
	overrides: 'GUIItem#disable',
	description: 'Disables this item.',
	memberof: 'Header',
	thisvalue: undefined,
	chainable: true,
	meta:
     { lineno: 56,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 84 },
{ id: 'Header#destroy',
	longname: 'Header#destroy',
	name: 'destroy',
	kind: 'function',
	scope: 'instance',
	inherits: 'GUIItem#destroy',
	inherited: true,
	overrides: 'GUIItem#destroy',
	memberof: 'Header',
	thisvalue: undefined,
	meta:
     { lineno: 65,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 85 },
{ id: 'GUI#enable',
	longname: 'GUI#enable',
	name: 'enable',
	kind: 'function',
	scope: 'instance',
	inherits: 'GUIItem#enable',
	inherited: true,
	overrides: 'GUIItem#enable',
	description: 'Enables or sets the enabled state of this item.',
	memberof: 'GUI',
	params: [ [ Object ] ],
	examples:
     [ 'controller.enable();\ncontroller.enable( false ); // disable\ncontroller.enable( controller.__disabled ); // toggle' ],
	thisvalue: undefined,
	chainable: true,
	meta:
     { lineno: 46,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 89 },
{ id: 'GUI#disable',
	longname: 'GUI#disable',
	name: 'disable',
	kind: 'function',
	scope: 'instance',
	inherits: 'GUIItem#disable',
	inherited: true,
	overrides: 'GUIItem#disable',
	description: 'Disables this item.',
	memberof: 'GUI',
	thisvalue: undefined,
	chainable: true,
	meta:
     { lineno: 56,
     	filename: 'lil-gui.module.js',
     	path: '/Users/georgebrower/Sites/@georgealways/gui/build' },
	order: 90 } ];
