import fs from 'fs';
import webfont from 'webfont';

const INPUT = 'style/icons/*.svg';
const OUTPUT = 'style/icons.scss';
const FONT_NAME = 'lil-gui';

const template = data => `// generated by scripts/icons.js
@font-face { 
	font-family: '${FONT_NAME}';
	src: url('data:application/font-woff;charset=utf-8;base64,${data}') format('woff');
}`;

webfont( {
	files: INPUT,
	fontName: FONT_NAME,
	format: 'woff'
} )
	.then( result => {
		const data = result.woff.toString( 'base64' );
		fs.writeFile( OUTPUT, template( data ), err => {
			if ( err ) throw err;
		} );
	} )
	.catch( err => {
		throw err;
	} );